export enum Pages {
    HOME = "/",
    START = "/start",
    SWAP = "/swap",
    MAP = "/map",
    LEADERBOARD = "/leaderboard",
    REWARDS = "/rewards",
    PROFILE = "/profile",
    SCROLLS = "/scrolls",
    INVENTORY = "/inventory",
    BONK_RUINS = "/bonk-ruins",
    TOWN_HALL = "/town-hall",
    TRAINING = "/start/training",
    BONK_RUINS_DEPOSIT = "/bonk-ruins/deposit",
    MINT_RUNE = "/mint/mint-rune",
    STEPS = "/mint/altar",
}